#!/usr/bin/bash
if [[ -z $ADDR ]]; then
	ADDR='CC:D3:C1:72:A6:8D'
fi;

# Check if the flag NO_SCAN=1 is set
if [[ -z $NO_SCAN ]]; then
        echo 'Scanning...'
        timeout --foreground --kill 10 5 bluetoothctl scan on
        EXIT=$?
        echo "Scan exited with code $EXIT"
        if [ $EXIT -eq 0 ]; then
                exit
        fi;
fi;

while [ 1 ]
do
	timeout --foreground --kill 10 10 bluetoothctl pair CC:D3:C1:72:A6:8D
	sleep 1
done
