#!/usr/bin/env bash
GIT_BRANCH_NAME="$(basename "$(git rev-parse --show-toplevel)")"
REMOVE_DIR=''
if [[ ! "$GIT_BRANCH_NAME" || "$GIT_BRANCH_NAME" != 'EEKIM10' ]]; then
    git clone git@github.com:EEKIM10/EEKIM10 /tmp/EEKIM10 || (rm -rf /tmp/EEKIM10 && exit $?)
    cd /tmp/EEKIM10 || exit 1
    REMOVE_DIR=/tmp/EEKIM10
fi;
if [[ $(basename "$(pwd)") != "dotfiles" ]]; then
    echo 'Changing to or making directory "dotfiles".'
    cd dotfiles || mkdir -p dotfiles
fi;

printf "Syncing .zshrc\n"
rsync -acp"$RSYNC_ARGS" "$HOME/.zshrc" .

printf "Syncing .zprofile\n"
rsync -acp"$RSYNC_ARGS" "$HOME/.zprofile" .

printf "Syncing .gitconfig\n"
rsync -acp"$RSYNC_ARGS" "$HOME/.gitconfig" .

printf "Syncing .wgetrc\n"
rsync -acp"$RSYNC_ARGS" "$HOME/.wgetrc" .

printf "Syncing .vimrc\n"
rsync -acp"$RSYNC_ARGS" "$HOME/.vimrc" .

printf "Syncing SSH Config\n"
rsync -acp"$RSYNC_ARGS" "$HOME/.ssh/config" ./.ssh/config

printf "Syncing NetworkManager.conf\n"
rsync -achP"$RSYNC_ARGS" /etc/NetworkManager/NetworkManager.conf ./NetworkManager/

printf "Syncing NetworkManager.conf.d\n"
rsync -achP"$RSYNC_ARGS" /etc/NetworkManager/conf.d ./NetworkManager/

printf "Syncing custom scripts from ~.local/bin/custom\n"
rsync -achpEP"$RSYNC_ARGS" "$HOME/.local/bin/custom/" ./scripts/

printf "Done syncing dotfiles.\n"

cd ..
_COMMIT=""
printf 'Press enter to commit & push... '
_COMMIT_READ=$(read -n 1 _COMMIT)
if [[ "$_COMMIT_READ" || -z "$_COMMIT" ]]; then
    echo 'Pulling...' && git pull
    git add .
        git commit -am "Update dotfiles (script-based)"

    _PUSH=""
    printf 'Press enter to push... '
    _PUSH_READ=$(read -n 1 _PUSH)
    if [[ "$_PUSH_READ" || -z "$_PUSH" ]]; then
        git push
    fi;
fi;

if [[ -n "$REMOVE_DIR" ]]; then
    rm -rfv "$REMOVE_DIR" | while read -r line; do
        printf "Removing: %s\33[2K\r" "$line"
    done;
    echo
fi;
