#!/usr/bin/env bash
if echo "$*" | grep -e '-v'; then
    VERBOSE=1
    echo verbose
else
    VERBOSE=0
fi

function run () {
    if [[ "$VERBOSE" -eq 1 ]]; then
        eval sudo "$*";
    else
        sudo "$@" 2>&1 |  while read -r line; do printf "\33[2K\r%s" "$line"; done
        echo;
    fi;
}

KERNEL_VERSION=$(uname -r)
COMMAND="/usr/bin/dracut --force --hostonly --no-hostonly-cmdline /usr/lib/modules/${KERNEL_VERSION}/initrd ${KERNEL_VERSION}"
echo "Generating regular boot image:  ${COMMAND}" > /dev/stderr
run $COMMAND
echo "Command exited with code $?." > /dev/stderr
echo
COMMAND="/usr/bin/dracut --force --hostonly /boot/initramfs-linux-fallback.img ${KERNEL_VERSION}"
echo "Generating fallback initramfs:  ${COMMAND}" > /dev/stderr
run $COMMAND
echo "Command exited with code $?." > /dev/stderr
