#!/usr/bin/env bash
GIT_BRANCH_NAME="$(basename "$(git rev-parse --show-toplevel)")"
if [[ ! "$GIT_BRANCH_NAME" || "$GIT_BRANCH_NAME" != 'EEKIM10' ]]; then
    git clone git@github.com:EEKIM10/EEKIM10 /tmp/EEKIM10 || (rm -rf /tmp/EEKIM10 && exit $?)
    cd /tmp/EEKIM10 || exit 1
fi;
if [[ $(basename "$(pwd)") != "custom" ]]; then
    cd custom || mkdir -p custom
fi;
rsync -apq "$HOME/.zshrc" .
rsync -apq "$HOME/.zprofile" .
rsync -apq "$HOME/.gitconfig" .
rsync -apq "$HOME/.wgetrc" .
rsync -avhP /etc/NetworkManager/NetworkManager.conf ./NetworkManager/
rsync -avhP /etc/NetworkManager/conf.d ./NetworkManager/
rsync -avhP ""$HOME/.local/bin/custom/"" ./scripts/
cd ..
_COMMIT_READ = read -p 'Press enter to commit & push' -n 1 _COMMIT
if [[ _COMMIT_READ ]] && [[ -z _COMMIT ]]; then
    git pull
    git add .
    git commit -am "Update dotfiles (script-based)"
fi;
