#!/usr/bin/bash
if [[ -z $ADDR ]]; then
	ADDR='CC:D3:C1:72:A6:8D'
fi;

echo 'Scanning...'
timeout --foreground --kill 10 5 bluetoothctl scan on
EXIT=$?
echo "Scan exited with code $EXIT"
if [ $EXIT -eq 0 ]; then
	exit
fi;

while [ 1 ]
do
	timeout --foreground --kill 5 5 bluetoothctl pair CC:D3:C1:72:A6:8D
	sleep 1
done
